version: '2'
services:
  logstash-collector:
    scale: 1
    start_on_create: true
    metadata:
      logstash:
        inputs: |
          beats {
            port => 5044
            tags => ["beats"]
          }
        outputs: |
          kafka {
            consumer_threads => 4
            topic_id => "mylogs"
          }
  logstash-indexer:
    scale: 1
    start_on_create: true
    metadata:
      logstash:
        inputs: |
          kafka {
            consumer_threads => 4
            group_id => "logstash"
            topics => ["mylogs"]
          }
        outputs: |
          elasticsearch {
            hosts => ["elasicsearch.rancher.internal:9200"]
          }
  redis:
    scale: 1
    start_on_create: true
