version: '2'
services:
  logstash-collector:
    image: docker.elastic.co/logstash/logstash:5.6.5
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - /etc/logstash/conf.d:/etc/logstash/conf.d
    links:
    - redis:redis
    ports:
    - 3520:3520/tcp
    user: logstash
    command:
    - logstash
    - -f
    - /etc/logstash/conf.d
    environment:
      xpack.monitoring.enabled: 'false'
    labels:
      io.rancher.scheduler.affinity:host_label: logstash=collector
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'

  logstash-indexer:
    image: docker.elastic.co/logstash/logstash:5.6.5
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - /etc/logstash/conf.d:/etc/logstash/conf.d
    links:
    - redis:redis
    external_links:
    - elasticsearch/es-master:elasticsearch
    command:
    - logstash
    - -f
    - /etc/logstash/conf.d
    environment:
      xpack.monitoring.enabled: 'false'
      XPACK_MONITORING_ENABLED: 'false'
      xpack.management.enabled: 'false'
      XPACK_MANAGEMENT_ENABLED: 'false'
    labels:
      io.rancher.scheduler.affinity:host_label_ne: logstash=collector
      io.rancher.container.hostname_override: container_name
