version: '2'
volumes:
  zkdata:
    driver: local
    per_container: true
    
  zkconfig:
    driver: local
    per_container: true
    
    
services:
  zk:
    image: rawmind/alpine-zk:3.4.10-0
    environment:
      CONFD_INTERVAL: '60'
      JVMFLAGS: -Xmx512m -Xms512m
      ZK_DATA_DIR: /opt/zk/data
      ZK_INIT_LIMIT: '10'
      ZK_MAX_CLIENT_CXNS: '500'
      ZK_SYNC_LIMIT: '5'
      ZK_TICK_TIME: '2000'
    tty: true
    volumes_from:
    - zk-volume
    - zk-conf
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.sidekicks: zk-volume,zk-conf
      io.rancher.container.hostname_override: container_name
      
  zk-conf:
    image: rawmind/rancher-zk:3.4.9
    network_mode: none
    volumes:
    - zkconfig:/opt/tools
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      
  zk-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10002'
      SERVICE_UID: '10002'
      SERVICE_VOLUME: /opt/zk/data
    network_mode: none
    volumes:
    - zkdata:/opt/zk/data
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
